var food = [
  {
    name: "Can eat",
    items: [
      "Bread",
      "Coconut",
      "Corn (not cob)",
      "Eggs (cooked)",
      "Honey",
      "Peanut butter / peanuts",
      "Quinoa",
      "Prawn",
      "Cooked rice",
      "Cooked pasta",
      "Watermelon",
      "Cucumbers",
      "Cheese",
      "Beans",
      "Weetbix",
      "Fish (skin is good)",
      "Popcorn",
      "Cherries (flesh only)",
      "Ginger",
      "Chickpea",
      "Cooked prawns",
      "Celery (leaves with caution)",
      "Pasta",
      "Tomato",
      "Pumpkin (flesh, seeds)",
    ],
  },
  {
    name: "Can eat some",
    items: [
      "Salt",
      "Milk",
      "Salty meats (ham, salami)",
      "Cashews",
      "Milk",
      "Sausage ",
      "Oats ",
      "Honey",
    ],
  },
  {
    name: "CANNOT EAT!",
    items: [
      "Chocolate",
      "Alcohol & meds (obviously)",
      "Chicken / cooked bones",
      "Grapes, raisins, currants",
      "Onion, garlic, chives",
      "Nuts (almonds, mac, pistachio, ect)",
      "Cinnamon",
      "Ice cream",
      "Xylitol??",
      "Coffee / tea",
      "Peach, plum, persimmon",
      "Raw egg",
      "Avocado",
      "Mushrooms",
      "Chewing gum",
      "Mouldy food / compost",
      "Corn cobs",
      "Fatty meats (offcuts)",
      "Tea",
      "tea tree oil ",
      "Cherry pips, stems, leaves (flesh is ok)",
      "Soft drink / ginger beer",
      "Falafel ",
      "Hommus",
      "Uncooked prawns",
      "Plum",
      "Vegemite",
      "Pumpkin skin, stem"
    ],
  },
];