var food = [
  {
    "name": "Can eat",
    "items": [
      "Apple",
      "Banana",
      "Beans",
      "Blackberries",
      "Blueberries",
      "Bread",
      "Broccoli",
      "Carrots (Small pieces)",
      "Celery (leaves with caution)",
      "Chicken (cooked, without bones)",
      "Chickpea",
      "Coconut",
      "Cooked prawns",
      "Cooked rice",
      "Corn (not cob)",
      "Cucumbers",
      "Eggs (cooked)",
      "Fish (skin is good)",
      "Ginger",
      "Mango",
      "Meat (Pork, Beef, Turkey, ect)",
      "Oats / Oatmeal",
      "Pasta",
      "Peanut butter",
      "Peas",
      "Popcorn",
      "Potato",
      "Pumpkin (flesh, seeds)",
      "Quinoa",
      "Strawberries",
      "Sweet Potato",
      "Watermelon",
      "Weetbix",
      "Yogurt"
    ]
  },
  {
    "name": "Limit / Caution",
    "items": [
      "Almonds",
      "Capsicum",
      "Cashews",
      "Cheese",
      "Cherries (flesh only)",
      "Honey",
      "Milk",
      "Peanuts",
      "Raw meat (careful)",
      "Salt",
      "Salty meats (ham, salami)",
      "Sausage ",
      "Tomato",
    ]
  },
  {
    "name": "CANNOT EAT!",
    "items": [
      "Alcohol & meds (obviously)",
      "Avocado",
      "Cherry pips, stems, leaves (flesh is ok)",
      "Chewing gum",
      "Chicken bones / cooked bones",
      "Chocolate",
      "Cinnamon",
      "Citrus, orange, lemon, lime",
      "Coconut products (water, milk, ect)",
      "Coffee / tea",
      "Corn cobs",
      "Falafel ",
      "Fatty meats (offcuts)",
      "Grapes, raisins, currants",
      "Hommus",
      "Ice cream",
      "Macadamia nuts",
      "Mouldy food / compost",
      "Mushrooms",
      "Nutmeg",
      "Onion, garlic, chives",
      "Peach, plum, persimmon",
      "Pineapple",
      "Pistachio nuts",
      "Pumpkin skin, stem",
      "Raw egg",
      "Raw yeast dough",
      "Soft drink / ginger beer",
      "Tea tree oil ",
      "Uncooked prawns",
      "Vegemite",
      "Xylitol (sugar substitute)"
    ]
  }
];